
import { Unit, Rank, ResourceGenerator, Weapon, Enemy, UnitRank } from './types';

export const WEAPONS: Record<string, Weapon> = {
  // Infantry Weapons
  'rifle_standard': {
    id: 'rifle_standard',
    name: 'Standard Issue Rifle',
    description: 'Reliable and balanced performance.',
    powerMultiplier: 1.0,
    craftingCost: {},
    unlockCost: {},
  },
  'rifle_high_caliber': {
    id: 'rifle_high_caliber',
    name: 'High-Caliber Rifle',
    description: 'Slower firing but packs a bigger punch.',
    powerMultiplier: 1.25,
    craftingCost: { gold: 50000, steel: 5000 },
    unlockCost: { gold: 5000, steel: 500 },
  },
  'rifle_burst_fire': {
    id: 'rifle_burst_fire',
    name: 'Burst-Fire Rifle',
    description: 'Fires in controlled bursts for improved accuracy and ammo conservation.',
    powerMultiplier: 1.15,
    craftingCost: { gold: 150000, steel: 10000 },
    unlockCost: { gold: 15000, steel: 1000 },
  },
  'sniper_rifle': {
    id: 'sniper_rifle',
    name: 'Barrett .50 Cal',
    description: 'A long-range, anti-materiel sniper rifle. Extreme power, very slow rate of fire.',
    powerMultiplier: 1.4,
    craftingCost: { gold: 250000, steel: 20000 },
    unlockCost: { gold: 25000, steel: 2000 },
  },
  // Vehicle Weapons
  'hmg_standard': {
    id: 'hmg_standard',
    name: 'Standard HMG',
    description: 'Standard heavy machine gun for vehicle mounting.',
    powerMultiplier: 1.0,
    craftingCost: {},
    unlockCost: {},
  },
  'cannon_rapid_fire': {
    id: 'cannon_rapid_fire',
    name: 'Rapid-Fire Cannon',
    description: 'Lower damage per shot, but a much higher rate of fire.',
    powerMultiplier: 1.4,
    craftingCost: { gold: 750000, steel: 100000 },
    unlockCost: { gold: 75000, steel: 10000 },
  },
  'grenade_launcher': {
    id: 'grenade_launcher',
    name: '40mm Grenade Launcher',
    description: 'Launches explosives for effective area suppression.',
    powerMultiplier: 1.3,
    craftingCost: { gold: 500000, steel: 50000 },
    unlockCost: { gold: 50000, steel: 5000 },
  },
  'flak_cannon': {
    id: 'flak_cannon',
    name: 'Flak Cannon',
    description: 'Fires shells that detonate mid-air, creating a cloud of shrapnel effective against aircraft.',
    powerMultiplier: 1.35,
    craftingCost: { gold: 900000, steel: 120000 },
    unlockCost: { gold: 90000, steel: 12000 },
  },
  // Tank Weapons
  'cannon_standard': {
    id: 'cannon_standard',
    name: '120mm Smoothbore',
    description: 'Standard main battle tank cannon.',
    powerMultiplier: 1.0,
    craftingCost: {},
    unlockCost: {},
  },
  'cannon_armor_piercing': {
    id: 'cannon_armor_piercing',
    name: 'Armor Piercing Shells',
    description: 'Deals significantly more damage.',
    powerMultiplier: 1.5,
    craftingCost: { gold: 5000000, steel: 1000000 },
    unlockCost: { gold: 500000, steel: 100000 },
  },
  'cannon_heat': {
    id: 'cannon_heat',
    name: 'HEAT Shells',
    description: 'High-Explosive Anti-Tank shells that melt through armor.',
    powerMultiplier: 1.6,
    craftingCost: { gold: 10000000, steel: 2500000 },
    unlockCost: { gold: 1000000, steel: 250000 },
  },
  'emp_cannon': {
    id: 'emp_cannon',
    name: 'EMP Cannon',
    description: 'Fires a non-lethal pulse that disables enemy electronics, rendering them vulnerable.',
    powerMultiplier: 1.7,
    craftingCost: { gold: 15000000, steel: 3000000 },
    unlockCost: { gold: 1500000, steel: 300000 },
  },
  // Air Weapons
  'missiles_standard': {
    id: 'missiles_standard',
    name: 'Standard Missiles',
    description: 'A standard missile payload.',
    powerMultiplier: 1.0,
    craftingCost: {},
    unlockCost: {},
  },
  'rockets_barrage': {
    id: 'rockets_barrage',
    name: 'Rocket Barrage',
    description: 'Unleashes a devastating barrage of unguided rockets.',
    powerMultiplier: 1.3,
    craftingCost: {}, // This is a default for the bomber
    unlockCost: { gold: 1000000, oil: 5000 },
  },
  'missiles_guided': {
    id: 'missiles_guided',
    name: 'Guided Missiles',
    description: 'Fire-and-forget missiles with superior tracking.',
    powerMultiplier: 1.4,
    craftingCost: { gold: 25000000, steel: 250000, oil: 100000 },
    unlockCost: { gold: 2500000, steel: 250000, oil: 10000 },
  },
  'plasma_cannon': {
    id: 'plasma_cannon',
    name: 'Plasma Cannons',
    description: 'Experimental energy weapons for ultimate air superiority.',
    powerMultiplier: 1.8,
    craftingCost: { gold: 500000000, oil: 1000000 },
    unlockCost: { gold: 50000000, oil: 100000 },
  },
  'laser_system': {
    id: 'laser_system',
    name: 'Gatling Laser System',
    description: 'A high-energy laser weapon that shreds targets with focused light.',
    powerMultiplier: 1.6,
    craftingCost: { gold: 250000000, oil: 500000 },
    unlockCost: { gold: 25000000, oil: 50000 },
  },
  'bomb_carpet': {
    id: 'bomb_carpet',
    name: 'Carpet Bombing Bay',
    description: 'Drops a massive payload of bombs to saturate a large area.',
    powerMultiplier: 1.5,
    craftingCost: { gold: 30000000000, steel: 2500000000, oil: 120000000 },
    unlockCost: { gold: 3000000000, steel: 250000000, oil: 12000000 },
  },
  'stealth_missiles': {
    id: 'stealth_missiles',
    name: 'Stealth Missiles',
    description: 'Missiles with a low radar cross-section, making them difficult to intercept.',
    powerMultiplier: 1.7,
    craftingCost: { gold: 750000000, oil: 1500000 },
    unlockCost: { gold: 75000000, oil: 150000 },
  },
  // Naval Weapons
  'naval_gun_standard': {
    id: 'naval_gun_standard',
    name: '5-inch Naval Gun',
    description: 'Standard cannon for naval vessels.',
    powerMultiplier: 1.0,
    craftingCost: {},
    unlockCost: {},
  },
  'railgun_prototype': {
    id: 'railgun_prototype',
    name: 'Railgun Prototype',
    description: 'Electromagnetically launched projectile dealing immense damage.',
    powerMultiplier: 1.6,
    craftingCost: { gold: 10000000000, steel: 2500000000, oil: 5000000 },
    unlockCost: { gold: 1000000000, steel: 250000000, oil: 500000 },
  },
  'missile_battery': {
    id: 'missile_battery',
    name: 'Tomahawk Missiles',
    description: 'Long-range cruise missiles for devastating precision strikes.',
    powerMultiplier: 1.4,
    craftingCost: { gold: 2500000000, steel: 500000000, oil: 10000000 },
    unlockCost: { gold: 250000000, steel: 50000000, oil: 1000000 },
  },
  'point_defense_system': {
    id: 'point_defense_system',
    name: 'Point-Defense System',
    description: 'Automated turrets providing a screen of defensive fire, increasing overall combat effectiveness.',
    powerMultiplier: 1.2,
    craftingCost: { gold: 750000000000, steel: 150000000000, oil: 3000000000 },
    unlockCost: { gold: 75000000000, steel: 15000000000, oil: 300000000 },
  },
  'artillery_cannon': {
    id: 'artillery_cannon',
    name: '16-inch Artillery',
    description: 'Massive naval guns for long-range shore bombardment and ship-to-ship combat.',
    powerMultiplier: 1.7,
    craftingCost: { gold: 15000000000, steel: 3000000000, oil: 6000000 },
    unlockCost: { gold: 1500000000, steel: 300000000, oil: 600000 },
  },
};

export const UNIT_RANKS: UnitRank[] = [
  { name: 'Rookie', xpRequired: 0, powerBonusMultiplier: 1.0 },
  { name: 'Regular', xpRequired: 100, powerBonusMultiplier: 1.05 },
  { name: 'Hardened', xpRequired: 500, powerBonusMultiplier: 1.10 },
  { name: 'Veteran', xpRequired: 2500, powerBonusMultiplier: 1.20 },
  { name: 'Elite', xpRequired: 10000, powerBonusMultiplier: 1.35 },
];

export const INITIAL_UNITS: Unit[] = [
  {
    id: 'soldier',
    name: 'Rifleman',
    description: 'The backbone of any army. Cheap, effective in numbers, and endlessly versatile.',
    cost: { gold: 50 },
    craftingCost: {},
    basePower: 1,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/soldier/400/200',
    requiredRank: 0,
    armorLevel: 1,
    upgradeCostBase: { gold: 100 },
    availableWeaponIds: ['rifle_standard', 'rifle_high_caliber', 'rifle_burst_fire', 'sniper_rifle'],
    unlockedWeaponIds: ['rifle_standard'],
    currentWeaponId: 'rifle_standard',
    weaponLevels: { 'rifle_standard': 1, 'rifle_high_caliber': 1, 'rifle_burst_fire': 1, 'sniper_rifle': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 1,
  },
  {
    id: 'humvee',
    name: 'Armored Humvee',
    description: 'A fast, lightly armored vehicle for reconnaissance and fire support.',
    cost: { gold: 500, steel: 50 },
    craftingCost: {},
    basePower: 12,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/humvee/400/200',
    requiredRank: 1,
    armorLevel: 1,
    upgradeCostBase: { gold: 1000, steel: 100 },
    availableWeaponIds: ['hmg_standard', 'cannon_rapid_fire', 'grenade_launcher', 'flak_cannon'],
    unlockedWeaponIds: ['hmg_standard'],
    currentWeaponId: 'hmg_standard',
    weaponLevels: { 'hmg_standard': 1, 'cannon_rapid_fire': 1, 'grenade_launcher': 1, 'flak_cannon': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 2,
  },
  {
    id: 'tank',
    name: 'M1 Abrams Tank',
    description: 'The quintessential main battle tank. Heavy armor, powerful cannon.',
    cost: { gold: 10000, steel: 2500 },
    craftingCost: {},
    basePower: 250,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/tank/400/200',
    requiredRank: 2,
    armorLevel: 1,
    upgradeCostBase: { gold: 20000, steel: 5000 },
    availableWeaponIds: ['cannon_standard', 'cannon_armor_piercing', 'cannon_heat', 'emp_cannon'],
    unlockedWeaponIds: ['cannon_standard'],
    currentWeaponId: 'cannon_standard',
    weaponLevels: { 'cannon_standard': 1, 'cannon_armor_piercing': 1, 'cannon_heat': 1, 'emp_cannon': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 4,
  },
  {
    id: 'helicopter',
    name: 'Attack Helicopter',
    description: 'Provides close air support and anti-tank capabilities with a versatile missile payload.',
    cost: { gold: 150000, steel: 25000, oil: 500 },
    craftingCost: {},
    basePower: 3500,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/chopper/400/200',
    requiredRank: 3,
    armorLevel: 1,
    upgradeCostBase: { gold: 300000, steel: 50000, oil: 1000 },
    availableWeaponIds: ['missiles_standard', 'rockets_barrage', 'missiles_guided'],
    unlockedWeaponIds: ['missiles_standard'],
    currentWeaponId: 'missiles_standard',
    weaponLevels: { 'missiles_standard': 1, 'rockets_barrage': 1, 'missiles_guided': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 2,
  },
  {
    id: 'fighter_jet',
    name: 'F-22 Raptor',
    description: 'An advanced fighter jet that ensures air superiority through speed and advanced weaponry.',
    cost: { gold: 5000000, steel: 500000, oil: 10000 },
    craftingCost: {},
    basePower: 100000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/jet/400/200',
    requiredRank: 4,
    armorLevel: 1,
    upgradeCostBase: { gold: 10000000, steel: 1000000, oil: 20000 },
    availableWeaponIds: ['missiles_standard', 'plasma_cannon', 'laser_system', 'stealth_missiles'],
    unlockedWeaponIds: ['missiles_standard'],
    currentWeaponId: 'missiles_standard',
    weaponLevels: { 'missiles_standard': 1, 'plasma_cannon': 1, 'laser_system': 1, 'stealth_missiles': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 1,
  },
  {
    id: 'railgun_tank',
    name: 'Railgun Tank',
    description: 'An experimental tank that fires projectiles at hypersonic speeds using electromagnetic energy.',
    cost: { gold: 45000000, steel: 8000000, oil: 100000 },
    craftingCost: { gold: 150000000, steel: 25000000, oil: 500000 },
    basePower: 1200000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/railgun/400/200',
    requiredRank: 5,
    armorLevel: 1,
    upgradeCostBase: { gold: 90000000, steel: 16000000, oil: 200000 },
    availableWeaponIds: ['railgun_prototype', 'laser_system'],
    unlockedWeaponIds: ['railgun_prototype'],
    currentWeaponId: 'railgun_prototype',
    weaponLevels: { 'railgun_prototype': 1, 'laser_system': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 3,
  },
  {
    id: 'battleship',
    name: 'Destroyer',
    description: 'A versatile naval warship that projects power across the seas with its large-caliber guns.',
    cost: { gold: 80000000, steel: 15000000, oil: 250000 },
    craftingCost: {},
    basePower: 2000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/ship/400/200',
    requiredRank: 5,
    armorLevel: 1,
    upgradeCostBase: { gold: 160000000, steel: 30000000, oil: 500000 },
    availableWeaponIds: ['naval_gun_standard', 'railgun_prototype', 'missile_battery', 'artillery_cannon'],
    unlockedWeaponIds: ['naval_gun_standard'],
    currentWeaponId: 'naval_gun_standard',
    weaponLevels: { 'naval_gun_standard': 1, 'railgun_prototype': 1, 'missile_battery': 1, 'artillery_cannon': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 150,
  },
  {
    id: 'spectre_gunship',
    name: 'Spectre Gunship',
    description: 'A heavily-armed, ground-attack aircraft designed for loitering over the battlefield and delivering sustained fire.',
    cost: { gold: 95000000, steel: 12000000, oil: 800000 },
    craftingCost: { gold: 300000000, steel: 40000000, oil: 2500000 },
    basePower: 25000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/gunship/400/200',
    requiredRank: 6,
    armorLevel: 1,
    upgradeCostBase: { gold: 190000000, steel: 24000000, oil: 1600000 },
    availableWeaponIds: ['cannon_rapid_fire', 'flak_cannon', 'rockets_barrage'],
    unlockedWeaponIds: ['cannon_rapid_fire'],
    currentWeaponId: 'cannon_rapid_fire',
    weaponLevels: { 'cannon_rapid_fire': 1, 'flak_cannon': 1, 'rockets_barrage': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 5,
  },
  {
    id: 'stealth_bomber',
    name: 'B-2 Spirit',
    description: 'A strategic bomber with stealth technology, capable of penetrating enemy air defenses undetected.',
    cost: { gold: 1200000000, steel: 100000000, oil: 5000000 },
    craftingCost: {},
    basePower: 35000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/bomber/400/200',
    requiredRank: 6,
    armorLevel: 1,
    upgradeCostBase: { gold: 2400000000, steel: 200000000, oil: 10000000 },
    availableWeaponIds: ['rockets_barrage', 'plasma_cannon', 'bomb_carpet', 'stealth_missiles'],
    unlockedWeaponIds: ['rockets_barrage'],
    currentWeaponId: 'rockets_barrage',
    weaponLevels: { 'rockets_barrage': 1, 'plasma_cannon': 1, 'bomb_carpet': 1, 'stealth_missiles': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 2,
  },
   {
    id: 'stealth_helicopter',
    name: 'Stealth Helicopter',
    description: 'A silent hunter, equipped with radar-absorbent materials and advanced missile systems.',
    cost: { gold: 2500000000, steel: 200000000, oil: 15000000 },
    craftingCost: { gold: 8000000000, steel: 600000000, oil: 50000000 },
    basePower: 90000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/stealth-chopper/400/200',
    requiredRank: 7,
    armorLevel: 1,
    upgradeCostBase: { gold: 5000000000, steel: 400000000, oil: 30000000 },
    availableWeaponIds: ['missiles_guided', 'laser_system', 'stealth_missiles'],
    unlockedWeaponIds: ['missiles_guided'],
    currentWeaponId: 'missiles_guided',
    weaponLevels: { 'missiles_guided': 1, 'laser_system': 1, 'stealth_missiles': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 2,
  },
  {
    id: 'goliath_tank',
    name: 'Goliath Super Heavy Tank',
    description: 'A monstrous landship. Sacrifices speed for overwhelming firepower and nigh-impenetrable armor.',
    cost: { gold: 800000000, steel: 150000000, oil: 25000000 },
    craftingCost: { gold: 2400000000, steel: 450000000, oil: 75000000 },
    basePower: 300000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/goliath/400/200',
    requiredRank: 7,
    armorLevel: 1,
    upgradeCostBase: { gold: 1600000000, steel: 300000000, oil: 50000000 },
    availableWeaponIds: ['cannon_heat', 'emp_cannon', 'railgun_prototype'],
    unlockedWeaponIds: ['cannon_heat'],
    currentWeaponId: 'cannon_heat',
    weaponLevels: { 'cannon_heat': 1, 'emp_cannon': 1, 'railgun_prototype': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 10,
  },
  {
    id: 'carrier',
    name: 'Aircraft Carrier',
    description: 'A floating fortress and mobile airbase, the ultimate symbol of naval supremacy.',
    cost: { gold: 25000000000, steel: 5000000000, oil: 100000000 },
    craftingCost: {},
    basePower: 1000000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/carrier/400/200',
    requiredRank: 7,
    armorLevel: 1,
    upgradeCostBase: { gold: 50000000000, steel: 10000000000, oil: 200000000 },
    availableWeaponIds: ['naval_gun_standard', 'railgun_prototype', 'point_defense_system'],
    unlockedWeaponIds: ['naval_gun_standard'],
    currentWeaponId: 'naval_gun_standard',
    weaponLevels: { 'naval_gun_standard': 1, 'railgun_prototype': 1, 'point_defense_system': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 1200,
  },
  {
    id: 'aegis_cruiser',
    name: 'Aegis Missile Cruiser',
    description: 'A technologically advanced warship equipped with state-of-the-art missile systems for controlling the seas.',
    cost: { gold: 50000000000, steel: 8000000000, oil: 200000000 },
    craftingCost: { gold: 150000000000, steel: 25000000000, oil: 600000000 },
    basePower: 2000000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/aegis/400/200',
    requiredRank: 8,
    armorLevel: 1,
    upgradeCostBase: { gold: 100000000000, steel: 16000000000, oil: 400000000 },
    availableWeaponIds: ['missile_battery', 'point_defense_system', 'artillery_cannon'],
    unlockedWeaponIds: ['missile_battery'],
    currentWeaponId: 'missile_battery',
    weaponLevels: { 'missile_battery': 1, 'point_defense_system': 1, 'artillery_cannon': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 300,
  },
  {
    id: 'mech_warrior',
    name: 'Mech Warrior',
    description: 'A heavily armed and armored bipedal assault vehicle. The pinnacle of ground warfare technology.',
    cost: { gold: 100000000000, steel: 18000000000, oil: 500000000 },
    craftingCost: { gold: 350000000000, steel: 60000000000, oil: 2000000000 },
    basePower: 5000000000,
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/mech/400/200',
    requiredRank: 8,
    armorLevel: 1,
    upgradeCostBase: { gold: 200000000000, steel: 36000000000, oil: 1000000000 },
    availableWeaponIds: ['laser_system', 'railgun_prototype', 'plasma_cannon'],
    unlockedWeaponIds: ['laser_system'],
    currentWeaponId: 'laser_system',
    weaponLevels: { 'laser_system': 1, 'railgun_prototype': 1, 'plasma_cannon': 1 },
    veterancyRank: 0,
    xp: 0,
    crew: 1,
  }
];

export const RESOURCE_GENERATORS: ResourceGenerator[] = [
  {
    id: 'farmland',
    name: 'Farmland',
    description: 'Produces wheat to feed your army.',
    cost: { gold: 150 },
    production: { wheat: 10 },
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/farm/400/200',
  },
  {
    id: 'gold_mine',
    name: 'Gold Mine',
    description: 'Generates a steady stream of gold.',
    cost: { gold: 200 },
    production: { gold: 5 },
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/goldmine/400/200',
  },
  {
    id: 'steel_mill',
    name: 'Steel Mill',
    description: 'Produces steel for vehicles and armor.',
    cost: { gold: 1000 },
    production: { steel: 2 },
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/steelmill/400/200',
  },
  {
    id: 'oil_refinery',
    name: 'Oil Refinery',
    description: 'Refines crude oil for advanced units.',
    cost: { gold: 5000, steel: 500 },
    production: { oil: 1 },
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/oilrig/400/200',
  },
  {
    id: 'ammo_factory',
    name: 'Ammo Factory',
    description: 'Manufactures ammunition for your forces.',
    cost: { steel: 25000, oil: 500 },
    production: { ammo: 5 },
    owned: 0,
    imageUrl: 'https://picsum.photos/seed/ammofactory/400/200',
  }
];


export const RANKS: Rank[] = [
  { name: 'Private', powerRequired: 0, incomeBonus: 5 },
  { name: 'Sergeant', powerRequired: 500, incomeBonus: 25 },
  { name: 'Lieutenant', powerRequired: 10000, incomeBonus: 150 },
  { name: 'Captain', powerRequired: 250000, incomeBonus: 1000 },
  { name: 'Major', powerRequired: 5000000, incomeBonus: 7500 },
  { name: 'Colonel', powerRequired: 100000000, incomeBonus: 50000 },
  { name: 'General', powerRequired: 2500000000, incomeBonus: 400000 },
  { name: 'Five-Star General', powerRequired: 75000000000, incomeBonus: 3000000 },
  { name: 'Commander of Armies', powerRequired: 1000000000000, incomeBonus: 25000000 },
];

export const ENEMIES: Enemy[] = [
    {
        id: 'insurgents',
        name: 'Local Insurgents',
        description: 'A small, poorly equipped group. A good first test for your forces.',
        militaryPower: 250,
        scavengeRewards: {
            resources: { gold: 10000, steel: 500, ammo: 250, wheat: 1000 },
            hostages: 5
        },
        xpReward: 25,
        imageUrl: 'https://picsum.photos/seed/insurgents/400/200',
    },
    {
        id: 'militia',
        name: 'Organized Militia',
        description: 'Better trained and equipped, they use guerilla tactics.',
        militaryPower: 8000,
        scavengeRewards: {
            resources: { gold: 150000, steel: 10000, ammo: 1000, wheat: 5000 },
            weaponBlueprintIds: ['rifle_high_caliber'],
            hostages: 10
        },
        xpReward: 100,
        imageUrl: 'https://picsum.photos/seed/militia/400/200',
    },
    {
        id: 'rogue_state',
        name: 'Rogue State Army',
        description: 'A conventional army with tanks and older-generation vehicles.',
        militaryPower: 500000,
        scavengeRewards: {
            resources: { gold: 2500000, steel: 500000, oil: 1000, ammo: 5000, wheat: 25000 },
            weaponBlueprintIds: ['grenade_launcher'],
            hostages: 20
        },
        xpReward: 500,
        imageUrl: 'https://picsum.photos/seed/rogue/400/200',
    },
    {
        id: 'syndicate',
        name: 'Crime Syndicate',
        description: 'A wealthy and technologically advanced criminal organization.',
        militaryPower: 10000000,
        scavengeRewards: {
            resources: { gold: 50000000, steel: 10000000, oil: 25000, ammo: 25000, wheat: 100000 },
            weaponBlueprintIds: ['cannon_armor_piercing'],
            hostages: 35
        },
        xpReward: 2500,
        imageUrl: 'https://picsum.photos/seed/syndicate/400/200',
    },
    {
        id: 'mega_corp',
        name: 'MegaCorp Taskforce',
        description: 'A private military contractor with cutting-edge fighter jets and naval support.',
        militaryPower: 250000000,
        scavengeRewards: {
            resources: { gold: 1000000000, steel: 250000000, oil: 500000, ammo: 100000, wheat: 500000 },
            weaponBlueprintIds: ['missiles_guided', 'laser_system'],
            hostages: 50
        },
        xpReward: 10000,
        imageUrl: 'https://picsum.photos/seed/megacorp/400/200',
    },
    {
        id: 'alien_scouts',
        name: 'Alien Scouting Party',
        description: 'Extraterrestrial visitors with unknown technology and motives. Highly dangerous.',
        militaryPower: 10000000000,
        scavengeRewards: {
            resources: { gold: 50000000000, steel: 10000000000, oil: 250000000, ammo: 5000000, wheat: 0 },
            weaponBlueprintIds: ['plasma_cannon'],
            hostages: 0
        },
        xpReward: 50000,
        imageUrl: 'https://picsum.photos/seed/aliens/400/200',
    },
    {
        id: 'final_boss',
        name: 'The Overlord',
        description: 'The ultimate threat. All your training has led to this moment.',
        militaryPower: 5000000000000,
        scavengeRewards: {
            resources: { gold: 10000000000000, steel: 1000000000000, oil: 100000000000, ammo: 1000000000, wheat: 0 },
            weaponBlueprintIds: ['railgun_prototype'],
            hostages: 0
        },
        xpReward: 250000,
        imageUrl: 'https://picsum.photos/seed/overlord/400/200',
    },
];
